apiVersion: skaffold/v4beta14
kind: Config
metadata:
    name: micro-services-advanced
manifests:
    rawYaml:
        - ./infra/k8s/*
deploy:
    kubectl: {}
build:
    googleCloudBuild:
        projectId: microservices-dev-501411
    artifacts:
        - image: us.gcr.io/microservices-dev-501411/auth
          context: auth
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - dest: .
                    src: 'src/**/*.ts'
