import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import getCurrentUser from '@/services/user-service';
import HeaderComponent from '@/components/header';
import { CurrentUserProvider } from '@/context/user-context';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Ticketing Dev',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentUser = await getCurrentUser();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col mx-1">
        <CurrentUserProvider currentUser={currentUser}>
          <HeaderComponent currentUser={currentUser} />
          <div className="container mx-auto">{children}</div>
        </CurrentUserProvider>
      </body>
    </html>
  );
}
