apiVersion: apps/v1
kind: Deployment
metadata:
    name: client-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: client
    template:
        metadata:
            labels:
                app: client
        spec:
            # Every Pods
            containers:
                - name: client
                  image: vladinson009/client
                  env:
                      - name: NEXT_PUBLIC_STRIPE_KEY
                        value: pk_test_51U7akOFydpBeTXgEc7q22bM1Ky1yRQ9zGtfOm6RO80MPhHcvvQUtTa85Ro9WCdOKad4qwu1QPiUm3JeMwl5jlpgv00ZVgPg8to

---
apiVersion: v1
kind: Service
metadata:
    name: client-srv
spec:
    selector:
        app: client
    ports:
        - name: client
          protocol: TCP
          port: 3000
          targetPort: 3000
