apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  ingressClassName: nginx
  rules:
    - host: localhost
      http:
        paths:
          # The order of paths is important. The / Path will match all as a wild card
          - pathType: ImplementationSpecific
            path: '/api/users(/|$)(.*)'
            backend:
              service:
                name: auth-srv
                port:
                  number: 3000
          - pathType: ImplementationSpecific
            path: '/?(.*)'
            backend:
              service:
                name: client-srv
                port:
                  number: 3000
