name: tests-payments

on:
  pull_request:
    paths:
      - 'payments/**'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: cd payments && npm ci && npm run test:ci
