name: tests-tickets

on:
    pull_request:
        paths:
            - 'tickets/**'

jobs:
    build_and_test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7
            - run: cd tickets && npm install && npm run test:ci