name: tests-orders

on:
    pull_request

jobs:
    build_and_test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7
            - run: cd orders && npm install && npm run test:ci